### PR TITLE
3581 api updates for biorxiv

### PR DESCRIPTION
**Pull request by alinvetian**
Closes: https://github.com/datadryad/dryad-product-roadmap/issues/3581

* API updates
* Added publication ISSN to be indexed in SOLR

### CODE REVIEW

**Comment by ryscher** [comment]
Converted to draft, pending email text from https://github.com/datadryad/dryad-product-roadmap/issues/3581

**Comment by ryscher** [comment]
The `modifiedBefore` search parameter is working correctly. However, for both this parameter and the existing `modifiedSince`, they are not accepting shortened forms of the date string. (Swagger documentation says "Shortened versions of the time string are acceptable, e.g., 2020-10.") I recommend we remove that note from the documentation, rather than trying to make the parsing more flexible.

**Comment by ryscher** [comment]
I tried to test the `journalISSN` parameter on dev after updating the SOLR config and reindexing, but I was not able to get it to work. Will need more testing.

**Comment by ryscher** [comment]
The email trigger appears to be working, if the `deliver_now` is used. Once the other changes are in place I want to test this more fully on sandbox.

**Review by ryscher — CHANGES_REQUESTED** [review]

**Comment by alinvetian** [comment]
@ryscher all requested updates are done

**Review by ryscher — APPROVED** [review]

**Comment by ryscher** [comment]
Email processing is working correctly. Still testing SOLR.

**Pull request merged**
